#specs for travis ci
language: python
dist: xenial
os: linux

stages:
  - latest-pythons

jobs:
  include:
    - env: ISOLATED=true
      dist: xenial
      python: '3.7'
      stage: latest-pythons
      before_install:
        - pip install -U pip
        - pip install pytest==5.4.1 codecov pytest-cov
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
      install:
        - pip install -e .
      before_script:
        - ./scripts/download_test_dataset.sh
      script:
        - pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID
