# specs for travis ci
language: python
python:
  - 3.6
# - 3.7 enable once supported by travis
# get the dependencies
install:
  - pip install .
# install what we need for testing
before_install:
  - pip install --upgrade pip
  - pip install pytest codecov
  - pip install "pytest-cov>=2.4.0,<2.6"
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

# script for tests... (eventually add coveralls)
before_script: make
script: pytest --cov=./moseq2_model
after_success:
  - codecov -t 0920ece4-7a13-4764-9ec2-192f709670ca
