#specs for travis ci
language: python
dist: trusty
os: linux

stages:
  - latest-installs
  - name: latest-pythons
    if: branch = master

jobs:
  include:
    - env: ISOLATED=true
      python: '3.6'
      stage: latest-installs
      before_install:
        - pip install -U pip
        - pip install pipenv codecov
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
      install:
        - pipenv install --dev --ignore-pipfile --deploy
        - pipenv run pip install git+https://github.com/mattjj/pyhsmm.git
        - pipenv run pip install git+https://github.com/mattjj/pybasicbayes.git
        - pipenv run pip install git+https://github.com/dattalab/pyhsmm-autoregressive.git@master
      before_script:
        - make
      script:
        - pipenv run pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID

    - env: ISOLATED=true
      dist: xenial
      python: '3.7'
      stage: latest-pythons
      before_install:
        - pip install -U pip
        - pip install pipenv codecov
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
      install:
        - pipenv install --dev --ignore-pipfile --deploy
        - pipenv run pip install git+https://github.com/mattjj/pyhsmm.git
        - pipenv run pip install git+https://github.com/mattjj/pybasicbayes.git
        - pipenv run pip install git+https://github.com/dattalab/pyhsmm-autoregressive.git@master
      before_script:
        - make
      script:
        - pipenv run pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID

    - env: ISOLATED=true
      python: '3.6'
      stage: latest-installs
      before_install:
        - pip install -U pip
        - pip install awscli
        - pip install pytest==5.4.1 codecov pytest-cov
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
      install:
        - pip install -e .
      before_script:
        - make
      script:
        - pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID

    - env: ISOLATED=true
      dist: xenial
      python: '3.7'
      stage: latest-pythons
      before_install:
        - pip install -U pip
        - pip install awscli
        - pip install pytest==5.4.1 codecov pytest-cov
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
      install:
        - pip install -e .
      before_script:
        - make
      script:
        - pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID
